// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace SettingsSearch
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "SettingsSearch";
        public const string Version     = "1.1.0";
        public const string Title       = "Settings Search";
        public const string Description = "Adds a search bar to the options menu to quickly find any mod's settings";
    }
}
